<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Deliverydate
 * @version    1.3.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 */
?>
<?php
?>
<?php if (1 || Mage::getStoreConfig(AW_Sarp_Helper_Config::XML_PATH_APPEARANCE_SHOW_POSTMAN_NOTICE)): ?>
    <dl>
        <dt class="input-box">
        <strong><?php echo $this->__("Delivery Date"); ?></strong>
        </dt>
        <dd><div><?php echo $this->getCalendarHtml() ?></div>
            <?php if (Mage::getStoreConfig(AW_Deliverydate_Helper_Config::XML_PATH_GENERAL_TIME_NOTICE_ENABLED)): ?>
                <i><?php echo $this->__("Please note that orders after %s will be delivered the next day", $this->getFormattedTime()) ?></i>
            <?php endif; ?>
        </dd>

        <?php if (Mage::getStoreConfig(AW_Deliverydate_Helper_Config::XML_PATH_GENERAL_NOTICE_ENABLED)): ?>
            <dt class="input-box">
            <strong><?php echo $this->__("Delivery Notice"); ?></strong>
            </dt>
            <dd><textarea name="aw_deliverydate_notice" cols="64" rows="10"><?php echo Mage::getSingleton('customer/session')->getAwDeliverydateNotice() ?></textarea></dd>
        <?php endif; ?>

    </dl>
<?php endif; ?> 
<?php echo $this->getChildHtml('deliverydate_html_calendar'); ?>