<div class="account-create">
<br />
<br />
<div class="page-title">

   <h1><?php echo $this->__('Create an Account') ?></h1>

</div>

 

    <?php echo $this->getChildHtml('form_fields_before')?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">

<div class="fieldset">
            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />

<h2 class="legend"><?php echo $this->__('Personal Information') ?></h2>
<p>
 
<ul class="form-list">

<li class="fields">
                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
</li>

<li>
             <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
             
<!---------------------------part 2 add line of code---------------------------->
<input type="hidden" name="group_id" id="group_id" value="2" />
<!---------------------------part 2 add line of code---------------------------->

             
             <div class="input-box">
             <input type="text" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
             </div>
</li>

<?php if ($this->isNewsletterEnabled()): ?>
   <li class="control">
      <div class="input-box">
         <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" /> <label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
      </div>      
   </li>
   <p>
   <p>
<?php endif ?>

<?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
<?php if ($_dob->isEnabled()): ?> 
<li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
<p>
<p>
<?php endif ?>

<?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
<?php if ($_taxvat->isEnabled()): ?>
<li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
<p> 
<p>
<?php endif ?>

<?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
<?php if ($_gender->isEnabled()): ?>
<li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
<p>
<p>
<?php endif ?>
                
 
 <!-----------custom field if needed------------
<li>
<br />
<br />
<div class="field">
<label for="your_cusom_field" class="required"><em>*</em><?php echo $this->__('Your Custom Field');?></label>
<br />
<div class="input-box">
   <input type="text" name="your_cusom_field" id="your_cusom_field" value="" title="<?php echo $this->__('Your Custom Field');?>" class="input-text required-entry">
</div>
</div>
</li> -------------->

            </ul>
<p>
 
<p>
        </div>

    <?php if($this->getShowAddressFields()): ?>

<div class="fieldset">
    <input type="hidden" name="create_address" value="1" />

<h2 class="legend"><?php echo $this->__('Address Information') ?></h2>
<br/>

<ul class="form-list">

<li class="fields">

     <div class="field">
     <label for="company"><?php echo $this->__('Company') ?></label>

     <div class="input-box">
     <input type="text" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
      </div>
     </div>


     <div class="field">
     <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>

     <div class="input-box">
     <input type="text" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
     </div>
     <p> 
     </div>
     <p>
     <p>
</li>
   
     
<?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>


<li class="wide">
      <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
      <div class="input-box">
      <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
      </div>
</li>
      
    
<?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
<?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>


<li class="wide">
  <div class="input-box">
  <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i)) ?>" title="  <?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
  </div>
</li>


<?php endfor; ?>


<br/>
<li class="fields">
   <div class="field">
      <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
      <div class="input-box">
      <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo $this->__('City') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
      </div>
   </div>


   <div class="field">
      <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>

      <br />
      <div class="input-box">
      <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
      <br />
      <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
      <p>
      <p>
      </select>
      <p>
      <p>
      <script type="text/javascript">
                            //<![CDATA[
                                $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                            //]]>
      </script>
      <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
   </div>
   </div>
</li>


<li class="fields">
   <div class="field">
   <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
   <br />
   <div class="input-box">
   <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
   </div>
   </div>
   <div class="field">
                        <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
   <br />
   <div class="input-box">
   <?php echo $this->getCountryHtmlSelect() ?>
   </div>
   </div>
</li>
</ul>
<p>
<p>
            <input type="hidden" name="default_billing" value="1" />
            <input type="hidden" name="default_shipping" value="1" />
</div>


<?php endif; ?>


<div class="fieldset">
   <h2 class="legend"><?php echo $this->__('Login Information') ?></h2>

   <ul class="form-list">

      <li class="fields">

         <div class="field">
            <br/>
            <label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
            <br />

            <div class="input-box">
               <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
            </div>
            <p>
            <p>
         </div>
            <br/>

            <div class="field">
            <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
            <br />
<div class="input-box">
                            <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
                        </div>
                    </div>
                </li>

                <?php echo $this->getChildHtml('form.additional.info'); ?>
                <?php echo $this->getChildHtml('persistent.remember.me'); ?>
            </ul>
<p>
 
<p>
            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
        </div>
<p>


<div >
   <div style="margin-left:20px; color:red; float:left;"><?php echo $this->__('* Required Fields') ?></div>
   <p>
   <p>

<!------- Back button---------
   <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link"><small>« </small><?php echo $this->__('Back') ?></a></p>  ------->
   <p>
   <p>
   <button style="margin-left:55px; border: 3px solid #92ae25 !important; width:100px !important;" type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
</div>



   <p>
 
<p>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>
<p>
 
<p>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>
    //]]>
    </script>
</div>
<p>
 
<p>
