<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 * 
 * please put <?php echo $this->getChildHtml('lightbox'); ?> in head.phtml to get woring light box
 * 
 */
?>
<script type="text/javascript">
    var fileLoadingImage = "<?php echo $this->getSkinUrl("wholesaler/images/loading.gif"); ?>";				// Loading image		
    var fileBottomNavCloseImage = "<?php echo $this->getSkinUrl("wholesaler/images/closelabel.gif"); ?>";		// Close image
    var fallbackOverlayImage = "<?php echo $this->getSkinUrl("wholesaler/images/overlay.png"); ?>";
</script>