<?php
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 * 
 * 
 * function $this->getWholesalers()
 * 
 * returns
 * 
 * 

  Array
  (
  [Wholesaler 1] => Array
  (
  [title] => Wholesaler 1
  [image] => http://localhost/projects/YoungOnes/media/AS_Wholesaler/1.jpeg
  [content] => this is the sample text for wholesaler
  )
 * )
 */
?>
<?php
$data = $this->fetchCorporateData();
?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="page-title">
    <h1><?php echo Mage::helper('contacts')->__('Corporate Accounts') ?></h1>
</div>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('content_corporate')->toHtml() ?> 
<form method="post" id="wholesaleaccountform" action="<?php echo $this->getUrl("wholesaler/corporate/save",array(
    '_secure' => true)) ?>">
    <input type="hidden" value="<?php echo Mage::app()->getStore()->getStoreId(); ?>" name="status"/>
    <input type="hidden" value="<?php echo Mage::getSingleton("core/session")->getFormKey(); ?>" name="form_key"/>
    <input type="hidden" value="<?php echo $data["id"]; ?>" name="id"/>
    <?php /* ?><input type="hidden" value="<?php echo Mage::app()->getStore()->getStoreId(); ?>" name="storeid"/>
    <input type="hidden" value="<?php echo Mage::app()->getStore()->getCode(); ?>" name="storecode"/>
    <input type="hidden" value="<?php echo Mage::app()->getLocale()->getLocaleCode(); ?>" name="storelocale"/> <?php */ ?>
    <input type="hidden" value="<?php echo $this->__("Corporate type") ?>" name="type"/>

    <div class="fieldset">
        <h2 class="legend"><?php echo Mage::helper('contacts')->__('Personal Information') ?></h2>
        <ul class="form-list">
            <li class="fields">
                <div class="customer-name">
                    <div class="field name-firstname">
                        <label class="required" for="name"><em>*</em><?php echo Mage::helper('contacts')->__('Name') ?></label>
                        <div class="input-box">
                            <input type="text" class="input-text required-entry" value="<?php echo $data["name"]; ?>" title="<?php echo Mage::helper('contacts')->__('Name') ?>" placeholder="<?php echo Mage::helper('contacts')->__('Name') ?>" style="text-transform: none" id="name" name="name">
                        </div>
                    </div>
                </div>
            </li>
            <li class="fields">
                <div class="customer-name">
                    <div class="field name-firstname">
                        <label class="required" for="email"><em>*</em><?php echo Mage::helper('contacts')->__('Email') ?></label>
                        <div class="input-box">
                            <input type="text" class="input-text required-entry validate-email" value="<?php echo $data["email"]; ?>" title="<?php echo Mage::helper('contacts')->__('Email') ?>" placeholder="<?php echo Mage::helper('contacts')->__('Email') ?>" style="text-transform: none" id="email" name="email">
                        </div>
                    </div>
                    
                </div>
            </li>
            
        </ul>
    </div>

    <div class="fieldset">
        <h2 class="legend"><?php echo Mage::helper('contacts')->__('Business Information') ?></h2>
        <ul class="form-list">
            <li class="fields">
                <div class="customer-name">
                    <div class="field name-firstname">
                        <label class="required" for="company name"><em>*</em><?php echo Mage::helper('contacts')->__('Company Name') ?></label>
                        <div class="input-box">
                            <input type="text" class="input-text required-entry" value="<?php echo $data["companyname"]; ?>" title="<?php echo Mage::helper('contacts')->__('Company Name') ?>" placeholder="<?php echo Mage::helper('contacts')->__('Company Name') ?>" style="text-transform: none" id="companyname" name="companyname">
                        </div>
                    </div>
                    <div class="field name-lastname">
                        <label class="required" for="lastname"><?php echo Mage::helper('contacts')->__('Company Website') ?></label>
                        <div class="input-box">
                            <input type="text" class="input-text" value="<?php echo $data["companywebsite"]; ?>" title="<?php echo Mage::helper('contacts')->__('Company Website') ?>" placeholder="<?php echo Mage::helper('contacts')->__('Company Website') ?>" style="text-transform: none" id="companywebsite" name="companywebsite">
                        </div>
                    </div>
                </div>
            </li>
            <li class="fields">
                <div class="customer-name">
                    <div class="field name-firstname">
                        <label class="required" for="company address"><?php echo Mage::helper('contacts')->__('Company Address') ?></label>
                        <div class="input-box">
                            <input type="text" class="input-text" value="<?php echo $data["companyaddress"]; ?>" title="<?php echo Mage::helper('contacts')->__('Company Address') ?>" placeholder="<?php echo Mage::helper('contacts')->__('Company Address') ?>" style="text-transform: none" id="companyaddress" name="companyaddress">
                        </div>
                    </div>
                    
                </div>
            </li>
            <li class="fields">
                <div class="customer-name">
                    <div class="field name-firstname">
                        <label class="required" for="notes on corporate order"><?php echo Mage::helper('contacts')->__('Notes on corporate order') ?></label>
                        <div class="input-box">
                            <textarea class="input-text" value="" title="<?php echo Mage::helper('contacts')->__('Notes on corporate order') ?>" placeholder="<?php echo Mage::helper('contacts')->__('Notes on corporate order') ?>" style="text-transform: none" id="comments" name="notes"><?php echo $data["notes"]; ?></textarea>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="fieldset">
        <h2 class="legend"><?php echo Mage::helper('contacts')->__('Captcha'); ?></h2>
        <ul class="form-list">
            <li class="fields">
                <div class="customer-name">
                    <div class="field name-firstname" style="width: 100%;">
                        <label class="required" for="firstname"><em>*</em><?php echo Mage::helper('contacts')->__('Insert Captcha Code') ?></label>
                        <div style="clear: both;">
           <div class="input-box" style="float: left;">
            <input type="text" name="captchatext" id="captchatext" class="input-text required-entry"/>
        </div>                 
        <img src="<?php echo  $this->getUrl("wholesaler/index/captcha"); ?>" alt="<?php echo $this->__("validate")?>" style="float: left; padding-left: 16px;" id="captchaimage" name="captchaimage"/>
        
        <img alt="reload captcha" title="reload captcha" id="refresh" style="cursor: pointer;padding:4px 0 0 8px;float: left;" src="<?php echo $this->getskinurl("images/refresh.jpeg")?>"/>
        
        </div>
    </div>
                </div>
            </li>
        </ul>
</div>

    <div class="buttons-set">
        <p class="required"><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p>
        <p class="back-link"><a class="back-link" href="javascript:window.history.go(-1);"><small> </small><?php echo Mage::helper('contacts')->__('Back') ?></a></p>
        <button class="button" title="Submit" type="submit"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>
    </div>


    





</form>
<script type="text/javascript">
    $("refresh").observe("click",function(){
        var srcs = $("captchaimage").readAttribute("src");
        if(srcs.indexOf("temp") != -1)
        {
            srcsA = srcs.split("temp"); 
            srcs = srcsA[0];
        }
        var imgs = new Element("img",{"alt":"loading captchaimage...","id":"captchaimage","src":srcs+"temp/"+new Date().getTime()+"/","style":"float:left;padding-left:16px;"});
        $("captchaimage").remove();
        $("refresh").insert({"before":imgs});
    });
    //<![CDATA[
    var contactForm = new VarienForm('wholesaleaccountform', true);
    //]]>
</script>