<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 * 
 * 
 * function $this->getBanners()
 * 
 * returns
 * 
 * 

  Array
  (
    [Banner 1] => Array
        (
            [title] => Banner 1
            [image] => http://localhost/projects/YoungOnes/media/AS_Banner/1.jpeg
            [content] => this is the sample text for banner
        )
 * )
 */
?>
<link rel="stylesheet" href="<?php echo $this->getskinurl("css/flexslider.css")?>"/>
<script src="<?php echo $this->getskinurl("js/jquery.flexslider-min.js")?>" type="text/javascript"></script>
<script type="text/javascript">
var js = jQuery.noConflict();
js(window).load(function() {    
        js('.flexslider').flexslider();
});	
</script>
<?php
$bannerCollection = $this->getBanners();
?>
<div class="flexslider">
	    <ul class="slides">
	    	<?php
                foreach($bannerCollection as $banner)
                {
                    ?>
                <li style="cursor: pointer;" onclick="window.open('<?php echo $banner["link"]?>');">
                    <img width="1349" height="437" src="<?php echo $banner['image']?>" />
                <p class="flex-caption"><?php echo $banner["title"]?></p>
                </li>
                <?php
                }
                ?>
                
	    </ul>
</div>